// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/accounts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/accounts.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/accounts.post').default>>>>
    }
    '/api/admin/accounts/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/accounts/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/accounts/[id].patch').default>>>>
    }
    '/api/admin/accounts/:id/info': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/accounts/[id]/info.post').default>>>>
    }
    '/api/admin/accounts/:id/refresh-session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/accounts/[id]/refresh-session.post').default>>>>
    }
    '/api/admin/accounts/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/accounts/login.post').default>>>>
    }
    '/api/admin/accounts/refresh': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/accounts/refresh.post').default>>>>
    }
    '/api/admin/calls': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/calls.get').default>>>>
    }
    '/api/admin/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/config.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/config.put').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}